image: docker:latest

services:
  - docker:dind

stages:
  - build
  - test
  - stagin
  - deploy

variables:
  GITLAB_VHN_TEST_IMAGE: registry.gitlab.com/rafaell416/vanilla-hackernews:test
  GITLAB_VHN_STAGIN_IMAGE: registry.gitlab.com/rafaell416/vanilla-hackernews:latest
  GITLAB_DOCKER_LOGIN: docker login registry.gitlab.com -u gitlab-ci-token -p $ACCESS_TOKEN
  HEROKU_DOCKER_LOGIN: docker login -u _ -p $HEROKU_AUTH_TOKEN registry.heroku.com
  HEROKU_VHN_STAGIN_IMAGE: registry.heroku.com/vanilla-hackernews/web:latest

build:
  stage: build
  script:
    - $GITLAB_DOCKER_LOGIN
    - docker build -t $GITLAB_VHN_TEST_IMAGE .
    - docker push $GITLAB_VHN_TEST_IMAGE

test:
  stage: test
  script:
    - $GITLAB_DOCKER_LOGIN
    - docker run $GITLAB_VHN_TEST_IMAGE yarn test

stagin:
  stage: stagin
  script:
    - $GITLAB_DOCKER_LOGIN
    - docker pull $GITLAB_VHN_TEST_IMAGE
    - docker tag $GITLAB_VHN_TEST_IMAGE $GITLAB_VHN_STAGIN_IMAGE
    - docker push $GITLAB_VHN_STAGIN_IMAGE

deploy:
  stage: deploy
  script:
    - $GITLAB_DOCKER_LOGIN
    - docker pull $GITLAB_VHN_STAGIN_IMAGE
    - $HEROKU_DOCKER_LOGIN
    - docker tag $GITLAB_VHN_STAGIN_IMAGE $HEROKU_VHN_STAGIN_IMAGE
    - docker push $HEROKU_VHN_STAGIN_IMAGE
    - curl https://cli-assets.heroku.com/install.sh | sh
    - heroku container:release web --app vanilla-hackernews
